# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: cmts_altimetry_applications
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::jupyterlab=3.6.3
  - conda-forge::ipympl
  - conda-forge::ipywidgets
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::matplotlib
  - conda-forge::cartopy